### PR TITLE
Add editor block support

### PR DESCRIPTION
**Pull request by samwilson**
This is still a draft.

Bug: https://phabricator.wikimedia.org/T226870

### CODE REVIEW

**Comment by prtksxna** [comment]
🎉🥳 This is so cool, it already works perfectly!

***

Can we do something clever to automatically show this toolbar (and functionality):
Screenshot 2019-07-18 at 6 16 10 PM

Lets try to be closer to the default styling for the setup state:
Screenshot 2019-07-18 at 6 17 36 PM
I don't think we get this free, at least not until WordPress/gutenberg/issues/16283.

Should we hide the `input` and `label` once something has been entered? We could use the pencil icon to show a small popup that asks for another file name. That would make it consistent with how the normal image block works.

Should we show the citation information that will eventually show on the post?

**Comment by samwilson** [comment]
Great idea re the pencil icon in the toolbar, thanks!

I've updated this patch to work a bit better, and am thinking of merging it as-is, if it works, and then iterate to clean things up. Apart from the edit icon, it needs progress indicators, and debouncing on the form inputs.

I changed the Wikipedia input box into two, one for lang and one for title; I figure we could make the former an auto complete language lookup, and then the latter can autocomplete from Wikipedias. Hm, same of course with Commons, and wikidata at the moment wants an item ID, when it should really be the same autocomplete as searching on wikidata itself... all future improvements I hope!

**Comment by prtksxna** [comment]
> I've updated this patch to work a bit better, and am thinking of merging it as-is, if it works, and then iterate to clean things up. 

Makes sense.

> Apart from the edit icon, it needs progress indicators, and debouncing on the form inputs.

Edit and alignment icons. Yeah the current way of showing progress is a bit jarring (I see debounced typing in the label below?).

> I changed the Wikipedia input box into two, one for lang and one for title; I figure we could make the former an auto complete language lookup, and then the latter can autocomplete from Wikipedias.

I still see just one input field.


BTW, I noticed a weird left margin on the image and caption inside the editor. Also, could you enable issues on this repo?

**Comment by samwilson** [comment]
> > Apart from the edit icon, it needs progress indicators, and debouncing on the form inputs.
> 
> Edit and alignment icons. Yeah the current way of showing progress is a bit jarring (I see debounced typing in the label below?).

Yep, no good as it stands: it's sending a request on every keystroke, and displaying the results in the order they come in. It's possible to type quickly and have the results come back out of order, and be left with the wrong item! Sad.

> > I changed the Wikipedia input box into two, one for lang and one for title; I figure we could make the former an auto complete language lookup, and then the latter can autocomplete from Wikipedias.
> 
> I still see just one input field.

Hmm, I wonder what this is. I think there's some caching going on somewhere. Do you have `WP_DEBUG` on? Are you running from a checkout of the WP svn repo?
 
> BTW, I noticed a weird left margin on the image and caption inside the editor.

I've put the Wikipedia and Wikidata ones in blockquotes with zero styling so far. I figured I'd ask a friendly designer to tell me what to improve next. :-) The Commons one uses the standard caption system for photos, so themes already handle the styling for that.

> Also, could you enable issues on this repo?

Done. Good idea. I'd thought maybe I'd use the WP bug tracker, but things are easier here.

**Pull request merged**
